***🔵Support vector Machine using to find classification labels for images***

In [19]:
import pandas as pd 
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [20]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [21]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [26]:
digits.feature_names

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [25]:
dataset=pd.DataFrame(digits.data,columns=digits.feature_names)
dataset['target']=digits.target
dataset.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [31]:
from sklearn.model_selection import train_test_split
x=dataset.drop('target',axis=1)
y=dataset['target']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [36]:
x_train.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
1734        0.0        0.0        3.0       14.0        1.0        0.0   
855         0.0        0.0        9.0        9.0        4.0        0.0   
1642        0.0        0.0        0.0       10.0       13.0        3.0   
175         0.0        1.0       10.0       16.0       16.0       11.0   
925         0.0        0.0        6.0       14.0       13.0        3.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
1734        0.0        0.0        0.0        0.0  ...       11.0        0.0   
855         0.0        0.0        0.0        0.0  ...        0.0        0.0   
1642        0.0        0.0        0.0        0.0  ...        1.0        0.0   
175         0.0        0.0        0.0        5.0  ...        4.0        0.0   
925         0.0        0.0        0.0        0.0  ...        2.0        0.0   

      pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
1734        0.0        0.0        3.0       11.0       16.0       13.0   
855         0.0        0.0        6.0       16.0       14.0        3.0   
1642        0.0        0.0        2.0       11.0       13.0        6.0   
175         0.0        1.0       15.0       14.0       11.0        4.0   
925         0.0        0.0        4.0       15.0       16.0        9.0   

      pixel_7_6  pixel_7_7  
1734        4.0        0.0  
855         0.0        0.0  
1642        0.0        0.0  
175         0.0        0.0  
925         0.0        0.0  

[5 rows x 64 columns]

In [35]:
x_test.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
1245        0.0        0.0        0.0        7.0       12.0        0.0   
220         0.0        0.0       11.0       16.0        8.0        0.0   
1518        0.0        0.0        8.0       15.0       12.0        4.0   
438         0.0        0.0        2.0       12.0       12.0       12.0   
1270        0.0        2.0       13.0       16.0       10.0        0.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
1245        0.0        0.0        0.0        0.0  ...       16.0        2.0   
220         0.0        0.0        0.0        6.0  ...        0.0        0.0   
1518        0.0        0.0        0.0        5.0  ...        7.0        0.0   
438         9.0        2.0        0.0        0.0  ...        0.0        0.0   
1270        0.0        0.0        0.0        6.0  ...       14.0        0.0   

      pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
1245        0.0        0.0        0.0        9.0       14.0       14.0   
220         0.0        0.0       13.0       16.0       11.0        1.0   
1518        0.0        0.0       13.0       16.0       15.0        8.0   
438         0.0        0.0        3.0       15.0        3.0        0.0   
1270        0.0        3.0       15.0       16.0       16.0       10.0   

      pixel_7_6  pixel_7_7  
1245        5.0        0.0  
220         0.0        0.0  
1518        0.0        0.0  
438         0.0        0.0  
1270        1.0        0.0  

[5 rows x 64 columns]

In [64]:
from sklearn.svm import SVC
model=SVC(kernel='poly',C=10,gamma='scale')
model.fit(x_train,y_train)

SVC(C=10, kernel='poly')

In [46]:
model.predict(x_test)

array([6, 9, 3, 7, 2, 1, 5, 2, 5, 2, 1, 9, 4, 0, 4, 2, 3, 7, 8, 8, 4, 3,
       9, 7, 5, 6, 3, 5, 6, 3, 4, 9, 1, 4, 4, 6, 9, 4, 7, 6, 6, 9, 1, 3,
       6, 1, 3, 0, 6, 5, 5, 1, 9, 5, 6, 0, 9, 0, 0, 1, 0, 4, 5, 2, 4, 5,
       7, 0, 7, 5, 9, 5, 5, 4, 7, 0, 4, 5, 5, 9, 9, 0, 2, 3, 8, 0, 6, 4,
       4, 9, 1, 2, 8, 3, 5, 2, 9, 0, 4, 4, 4, 3, 5, 3, 1, 3, 5, 9, 4, 2,
       7, 7, 4, 4, 1, 9, 2, 7, 9, 7, 2, 6, 9, 4, 0, 7, 2, 7, 5, 8, 7, 5,
       7, 9, 0, 6, 6, 4, 2, 8, 0, 9, 4, 6, 9, 9, 6, 9, 0, 3, 5, 6, 6, 0,
       6, 4, 3, 9, 3, 7, 7, 2, 9, 0, 4, 5, 3, 6, 5, 9, 9, 8, 4, 2, 1, 3,
       7, 7, 2, 2, 3, 9, 8, 0, 3, 2, 2, 5, 6, 9, 9, 4, 1, 5, 4, 2, 3, 6,
       4, 8, 5, 9, 5, 7, 8, 9, 4, 8, 1, 5, 4, 4, 9, 6, 1, 8, 6, 0, 4, 5,
       2, 7, 4, 6, 4, 5, 6, 0, 3, 2, 3, 6, 7, 1, 5, 1, 4, 7, 6, 8, 8, 5,
       5, 1, 6, 2, 8, 8, 9, 5, 7, 6, 2, 2, 2, 3, 4, 8, 8, 3, 6, 0, 9, 7,
       7, 0, 1, 0, 4, 5, 1, 5, 3, 6, 0, 4, 1, 0, 0, 3, 6, 5, 9, 7, 3, 5,
       5, 9, 9, 8, 5, 3, 3, 2, 0, 5, 8, 3, 4, 0, 2,

***⚪now accuracy of the model by predicting the x test data and comapring y test data***

In [65]:
model.score(x_test,y_test)

0.9861111111111112